---
kind: "pipeline"
name: "container"

steps:
  - name: "container"
    image: "plugins/docker"
    settings:
      registry: "quay.io"
      repo: "quay.io/littlemanco/helm"
      username:
        from_secret: "DOCKER_USERNAME"
      password:
        from_secret: "DOCKER_PASSWORD"
        
trigger:
  branch:
    - master
  event:
    - push

